### ISSUE TITLE
Provide a version of the player that is not in an Activity

### ISSUE THREAD

**Issue by Desidiosus** [bambuser/BambuserPlayerSDK-Android#12]
The current Activity only version is unusable for more advanced use cases such as showing multiple small players in a view or simply embedding a video player in another view. As it stands, the only use case for the native SDK is showing a fullscreen player, which is very limiting and forces the usage of the less performant WebView player on Android for everything else. I get that it's an Activity for Picture-in-Picture support, but both variants could be offered to allow more flexibility for usage.

**Comment by emailvenkatm** [comment]
@zeyadsadaqa  Wondering if there is any update on this?

**Comment by zeyadsadaqa** [comment]
This should be fixed in the SDK version 2.1.1
