### ISSUE TITLE
 OnClose is not called when back button is clicked

### ISSUE THREAD

**Issue by SergioPoq** [bambuser/BambuserPlayerSDK-Android#16]
OnClose event is not called when `enablePictureInPicture = true` and the back button is clicked. The event is triggered correctly when we configure the player with `enablePictureInPicture = false`

**Comment by SimovicIvan** [comment]
Fixed in release [1.3.0](https://github.com/bambuser/BambuserPlayerSDK-Android/releases/tag/1.3.0)
