### ISSUE TITLE
ShowShoppingCart false does not hide the cart on end curtain

### ISSUE THREAD

**Issue by SergioPoq** [bambuser/BambuserPlayerSDK-Android#17]
If `showShoppingCart = false`, the cart icon is hidden from the show view but not from the end curtain screen

**Comment by zeyadsadaqa** [comment]
Thanks @SergioPoq for notifying us, the issue has been addressed and a fix will go in our next release

**Comment by SimovicIvan** [comment]
Fixed in release [1.3.0](https://github.com/bambuser/BambuserPlayerSDK-Android/releases/tag/1.3.0)
