### ISSUE TITLE
Product details page does not show from end curtain

### ISSUE THREAD

**Issue by SergioPoq** [bambuser/BambuserPlayerSDK-Android#18]
If `enableProductDetailsPage = true`, it is shown correctly when a product is clicked from the player screen but nothing happens when the user clicks on the product on the end curtain screen

**Comment by zeyadsadaqa** [comment]
Thanks @SergioPoq for notifying us, the issue has been addressed and a fix will go in our next release

**Comment by SimovicIvan** [comment]
Fixed in release [1.3.0](https://github.com/bambuser/BambuserPlayerSDK-Android/releases/tag/1.3.0)
