### ISSUE TITLE
Replay button does not work

### ISSUE THREAD

**Issue by SergioPoq** [bambuser/BambuserPlayerSDK-Android#25]
When a live show ends, the following screen shows and the replay button does nothing.
I am using Bambuser 1.3.0
[Screenshot](https://github.com/user-attachments/assets/d3e2a4fe-bd2d-4928-a93a-33a399227cc7)

**Comment by SimovicIvan** [comment]
Working on this now, should have a fix up soon.

**Comment by SimovicIvan** [comment]
Fixed in [1.3.2](https://github.com/bambuser/BambuserPlayerSDK-Android/releases/tag/1.3.2)
