### ISSUE TITLE
What's the reason for Android 8 as minimum supported version?

### ISSUE THREAD

**Issue by pvegh** [bambuser/BambuserPlayerSDK-Android#3]
As per documentation: Minimum supported version is Android 8 (API 26)
It is a little too high, since many apps today still support down to 23 (or even below), which would not be possible integrating this bambuser SDK. The current webview approach, while technically not optimal, supports those systems.

What's the technical reason behind it for the bambuser SDK?
What would it take to support SDK 23 aka Android 6?

**Comment by JennyBambuser** [comment]
Thank you for your feedback. After a quick check it looks like your suggestion would not require any major changes to the SDK.
The minimum version will most likely be lowered in an upcoming release.
