### ISSUE TITLE
Request for Native Mobile SDK Cart Integration Documentation

### ISSUE THREAD

**Issue by emailvenkatm** [bambuser/BambuserPlayerSDK-Android#30]
We are working on integrating Bambuser's shopping cart feature using the mobile SDK (for Android and iOS). While we have found the documentation for web here https://bambuser.com/docs/live/cart-integration, it seems there isn't equivalent documentation that outlines how to achieve similar functionality on native mobile apps.

We would like to request documentation or guidance on how to:

Provide detailed product data from the mobile side (similar to the PROVIDE_PRODUCT_DATA event in the web documentation) on to integrate the player with our internal API to fetch the product enrichment fields and use them in cart.

**Comment by zeyadsadaqa** [comment]
Hello Emailvenkatm! We have a quick guide documented in this [PR](https://github.com/bambuser/BambuserPlayerSDK-Android/pull/22/files)
Let me know if it has enough guidance for you to start integrating the cart into your app, or if you need more detailed information.

**Comment by emailvenkatm** [comment]
Thanks @zeyadsadaqa
