### ISSUE TITLE
Products Marked as Out of Stock Without Color and Size Variants

### ISSUE THREAD

**Issue by emailvenkatm** [bambuser/BambuserPlayerSDK-Android#31]
**Expected Behavior:**
Products without color or size variants should not automatically be considered out of stock. There should be a fallback for products that don't have these variants.

**Steps to Reproduce:**
1. Create a product without any `ColorVariant` or `SizeVariant` fields.
2. Load the product in the Bambuser player.
3. Observe that the product is displayed as "out of stock."

**Comment by zeyadsadaqa** [comment]
Thanks, Emailvenkatm for reaching out, we are going to look into it and get back to you

**Comment by zeyadsadaqa** [comment]
Hello @emailvenkatm 
I looked into this issue, and it seems that this was built like this by intention, each product should have at least one color variant with at least one size variant, this is mandatory to be able to detect the quantity of that variant.
We are working to make it more flexible in the future, but as for now just make sure to add a variant.

**Comment by emailvenkatm** [comment]
Got it.. Thanks @zeyadsadaqa
