### ISSUE TITLE
productReference Populated with publicUrl in Bambuser Android SDK

### ISSUE THREAD

**Issue by emailvenkatm** [bambuser/BambuserPlayerSDK-Android#32]
We are facing an issue with the Bambuser Android SDK where the productReference field is being populated with the value of publicUrl. This issue is only present on Android, but working as expected on iOS. This discrepancy is causing problems with our product linking and integration on Android.

**Comment by zeyadsadaqa** [comment]
Thanks @emailvenkatm for reaching out, we are going to take into that

**Comment by zeyadsadaqa** [comment]
@emailvenkatm This issue has been fixed in the latest version 2.0.0
