### ISSUE TITLE
Use OkHttp 4 stable instead of 5 alpha

### ISSUE THREAD

**Issue by pvegh** [bambuser/BambuserPlayerSDK-Android#5]
A library should not use unstable dependencies like
+|                   +--- com.squareup.okhttp3:okhttp:4.11.0 -> 5.0.0-alpha.11

While users of the library (bambuser customers) can technically workaround this, it's not a good practice to do this in a library.
The workaround means we have extra work and risks having to care about this at all.

**Comment by JennyBambuser** [comment]
Thank you for your feedback, changing this version will require some minor code changes on our side. We will update this in the future

**Comment by pvdmde** [comment]
To be clear, we cannot use this library until this is fixed.
