### ISSUE TITLE
Data missing from Events

### ISSUE THREAD

**Issue by pvegh** [bambuser/BambuserPlayerSDK-Android#7]
Compared to the webplayer and JS callbacks we used, multiple things are missing from the native SDK

The webplayer used a function like onShowShare(url: String) which we used to share the URL natively.

Currently the OnShare event only contains the playerId (unnecessary for now), but not the **URL** (would be necessary)

Also all the existing data is missing from the new OnPlay event. It was part of the web/JS solution
missing: **showId, title, isLive**
_onPlay(detail.data.title, detail.data.isLive);_ 

Also **showId**, **url** and **durationInMilliseconds** is missing in OnAddToCalendar. Is the date here the same value as  startDateString was in JS?

**Comment by JennyBambuser** [comment]
Thank you for your observation, these events will be updated in the next release. 

The date in `onAddToCalendar` is the scheduled start time of the show, it will be renamed to `scheduledStartDate` to clearify its purpose.

**Comment by SimovicIvan** [comment]
Finished in 1.1.5 release
