### ISSUE TITLE
Default SharedPreferences is cleared

### ISSUE THREAD

**Issue by SergioPoq** [bambuser/BambuserPlayerSDK-Android#9]
DefaultSharedPreferences is cleared after opening `LVSPlayer`. This means that if the app or any other SDK uses the default SharedPreferences, all its preferences are deleted.
If BambuserPlayerSDK needs to clear its SharedPreferences, it should create its own SharedPreference and not use the default one.

**Comment by JennyBambuser** [comment]
Thank you for your observation, we have updated this and it will be fixed in the next release

**Comment by SimovicIvan** [comment]
Fixed in 1.1.5
